# Generated by Django 4.2.7 on 2025-12-22 02:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='cursos.curso')),
                ('docente', models.ForeignKey(limit_choices_to={'tipo__in': ['docente', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones_dictadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tema', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_clase', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='cursos.promocion')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['promocion', 'numero_tema'],
                'unique_together': {('promocion', 'numero_tema')},
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_texto', models.TextField()),
                ('tipo_pregunta', models.CharField(choices=[('opcion_multiple', 'Opción Múltiple'), ('verdadero_falso', 'Verdadero/Falso'), ('texto', 'Texto Libre')], default='opcion_multiple', max_length=20)),
                ('opcion_a', models.CharField(blank=True, max_length=500, null=True)),
                ('opcion_b', models.CharField(blank=True, max_length=500, null=True)),
                ('opcion_c', models.CharField(blank=True, max_length=500, null=True)),
                ('opcion_d', models.CharField(blank=True, max_length=500, null=True)),
                ('respuesta_correcta', models.CharField(blank=True, max_length=10, null=True)),
                ('puntos', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='cursos.tema')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['tema', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='materiales/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='cursos.tema')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(limit_choices_to={'tipo': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='cursos.promocion')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('alumno', 'promocion')},
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tiempo_limite', models.PositiveIntegerField(blank=True, help_text='Tiempo en minutos', null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('preguntas', models.ManyToManyField(related_name='examenes', to='cursos.pregunta')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='cursos.tema')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_dada', models.TextField()),
                ('es_correcta', models.BooleanField(default=False)),
                ('puntos_obtenidos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='cursos.examen')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_examenes', to='cursos.inscripcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='cursos.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de Examen',
                'verbose_name_plural': 'Respuestas de Exámenes',
                'ordering': ['examen', 'inscripcion', 'pregunta'],
                'unique_together': {('examen', 'inscripcion', 'pregunta')},
            },
        ),
        migrations.CreateModel(
            name='CalificacionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('puntaje_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='cursos.examen')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_examenes', to='cursos.inscripcion')),
            ],
            options={
                'verbose_name': 'Calificación de Examen',
                'verbose_name_plural': 'Calificaciones de Exámenes',
                'ordering': ['-fecha_completado'],
                'unique_together': {('examen', 'inscripcion')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_asistencia', models.CharField(choices=[('presente', 'Presente'), ('tarde', 'Tarde'), ('presente_sin_camara', 'Presente sin cámara encendida'), ('no_asistio', 'No asistió')], default='no_asistio', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='cursos.inscripcion')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='cursos.tema')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['tema', 'inscripcion'],
                'unique_together': {('inscripcion', 'tema')},
            },
        ),
    ]
