# Generated by Django 4.2.7 on 2025-12-22 03:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromedioPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_final', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promedio', to='cursos.inscripcion')),
            ],
            options={
                'verbose_name': 'Promedio de Promoción',
                'verbose_name_plural': 'Promedios de Promociones',
                'ordering': ['-promedio_final'],
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_diploma', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_validez', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='cursos.inscripcion')),
            ],
            options={
                'verbose_name': 'Diploma',
                'verbose_name_plural': 'Diplomas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
