# Generated by Django 4.2.7 on 2025-12-22 03:32

from django.db import migrations, models
import django.db.models.deletion


def migrar_curso_desde_promocion(apps, schema_editor):
    """Migra el curso desde promocion a tema"""
    Tema = apps.get_model('cursos', 'Tema')
    for tema in Tema.objects.all():
        if tema.promocion:
            tema.curso = tema.promocion.curso
            tema.save()


def revertir_curso_a_promocion(apps, schema_editor):
    """Esta función no puede revertirse automáticamente"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_promediopromocion_diploma'),
    ]

    operations = [
        # Paso 1: Agregar campo curso como nullable
        migrations.AddField(
            model_name='tema',
            name='curso',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='temas',
                to='cursos.curso'
            ),
        ),
        # Paso 2: Migrar datos
        migrations.RunPython(migrar_curso_desde_promocion, revertir_curso_a_promocion),
        # Paso 3: Actualizar unique_together y ordering ANTES de eliminar promocion
        migrations.AlterUniqueTogether(
            name='tema',
            unique_together={('curso', 'numero_tema')},
        ),
        migrations.AlterModelOptions(
            name='tema',
            options={
                'ordering': ['curso', 'numero_tema'],
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        # Paso 4: Hacer curso no nullable
        migrations.AlterField(
            model_name='tema',
            name='curso',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='temas',
                to='cursos.curso'
            ),
        ),
        # Paso 5: Eliminar campo promocion
        migrations.RemoveField(
            model_name='tema',
            name='promocion',
        ),
    ]
