# Generated by Django 4.2.7 on 2025-12-22 03:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_cambiar_tema_a_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='preguntas',
        ),
        migrations.AddField(
            model_name='examen',
            name='numero_preguntas',
            field=models.PositiveIntegerField(default=10, help_text='Número de preguntas a seleccionar aleatoriamente del banco'),
        ),
        migrations.AddField(
            model_name='examen',
            name='puntos_por_pregunta',
            field=models.PositiveIntegerField(default=1, help_text='Puntos que vale cada pregunta', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='examen',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de fin del examen', null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de inicio del examen', null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='tema',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen', to='cursos.tema'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
