# Generated by Django 4.2.7 on 2025-12-22 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_cambiar_examen_one_to_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuperacionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora de inicio de la recuperación')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha y hora de fin de la recuperación')),
                ('activa', models.BooleanField(default=True)),
                ('completada', models.BooleanField(default=False, help_text='Indica si el estudiante ya realizó la recuperación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones', to='cursos.examen')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones_examenes', to='cursos.inscripcion')),
            ],
            options={
                'verbose_name': 'Recuperación de Examen',
                'verbose_name_plural': 'Recuperaciones de Exámenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='calificacionexamen',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='respuestaexamen',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calificacionexamen',
            name='recuperacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificacion', to='cursos.recuperacionexamen'),
        ),
        migrations.AddField(
            model_name='respuestaexamen',
            name='recuperacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='cursos.recuperacionexamen'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacionexamen',
            unique_together={('examen', 'inscripcion', 'recuperacion')},
        ),
        migrations.AlterUniqueTogether(
            name='respuestaexamen',
            unique_together={('examen', 'inscripcion', 'pregunta', 'recuperacion')},
        ),
    ]
