# Generated by Django 4.2.7 on 2025-12-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Forzar cambio de contraseña en próximo login'),
        ),
    ]
